paths:
  /api/productos/:
    get:
      summary: Obtiene todos los usuarios
      tags:
        - Productos
      responses:
        "200":
          description: Los usuarios fueron obtenidos exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Productos"
        "500":
          description: Error interno de server, puede generarse por una query defectuosa
